# Generated by Django 2.1.7 on 2019-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoiceNumber', models.IntegerField(unique_for_date=True)),
                ('petrolQuantity', models.IntegerField(blank=True)),
                ('dieselQuantity', models.IntegerField(blank=True)),
                ('lubricantQuantity', models.IntegerField(blank=True)),
                ('invoiceAmount', models.IntegerField()),
                ('cheque_demand_number', models.IntegerField()),
                ('paymentDate', models.DateField()),
                ('amountPaid', models.IntegerField()),
                ('amountRemainPaid', models.IntegerField()),
                # ('shortExcess', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
