# Generated by Django 2.1.7 on 2019-04-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMS_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='shortExcess',
            field=models.IntegerField(null=True),
        ),
    ]
