# Generated by Django 2.1.7 on 2019-04-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMS_backend', '0002_account_shortexcess'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('openingStock', models.FloatField(default=0)),
                ('receiptStock', models.FloatField(default=0)),
                ('totalStock', models.FloatField()),
                ('actualSale', models.FloatField(default=0)),
                ('closingStock', models.FloatField()),
                ('productDip', models.FloatField(default=0)),
                ('actualDip', models.FloatField(default=0)),
                ('variations', models.FloatField(default=0)),
                ('waterCm', models.FloatField(default=0)),
                ('waterLtrs', models.FloatField(default=0)),
            ],
        ),
    ]
