# Generated by Django 2.1.7 on 2019-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMS_backend', '0003_dieselstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselNozzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('openingReadingForNozzle1', models.FloatField()),
                ('openingReadingForNozzle2', models.FloatField()),
                ('openingReadingForNozzle3', models.FloatField()),
                ('openingReadingForNozzle4', models.FloatField()),
                ('saleForNozzle1', models.FloatField(default=0)),
                ('saleForNozzle2', models.FloatField(default=0)),
                ('saleForNozzle3', models.FloatField(default=0)),
                ('saleForNozzle4', models.FloatField(default=0)),
                ('totalMeterSale', models.FloatField()),
                ('testing', models.IntegerField(default=0)),
                ('rate', models.FloatField()),
                ('totalAmount', models.FloatField(default=0)),
            ],
        ),
    ]
