# Generated by Django 2.1.7 on 2019-04-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMS_backend', '0004_dieselnozzle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselDensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('morningObservedHydroDensity', models.FloatField(default=0)),
                ('morningObservedTemperatureDensity', models.FloatField(default=0)),
                ('morningDensity', models.FloatField(default=0)),
                ('receiptsInvoiceNumber', models.FloatField(default=0)),
                ('receiptsQuantity', models.FloatField(default=0)),
                ('receiptsObservedHydroDensity', models.FloatField(default=0)),
                ('receiptsObservedTemperatureDensity', models.FloatField(default=0)),
                ('receiptsDensity', models.FloatField(default=0)),
                ('asPerChallanDensity', models.FloatField(default=0)),
                ('decantationObservedHydroDensity', models.FloatField(default=0)),
                ('decantationObservedTemperatureDensity', models.FloatField(default=0)),
                ('decantationDensity', models.FloatField(default=0)),
                ('densityDifference', models.FloatField(default=0)),
            ],
        ),
    ]
