# Generated by Django 2.1.7 on 2019-04-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPMS_backend', '0005_dieseldensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieseldensity',
            name='decantationObservedHydroDensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dieseldensity',
            name='morningObservedHydroDensity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dieseldensity',
            name='receiptsInvoiceNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dieseldensity',
            name='receiptsQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
